data_description = {'Sales': 'Total number of homes sold in a month',
                    'Dollar Volume': 'Total price of all the houses sold in a month',
                    'Average Price': 'Average price of houses sold in a month',
                    'Median Price': 'Median price of houses sold in a month',
                    'New listings': 'Number of listings between the first day and last day of month',
                    'SNLR': 'Sales to New Listing ratio (12 months mov avg) for a month',
                    'Active listings': 'Number of active listings on the last day of month',
                    'MI': 'Months of inventory (12 months mov average of active listings/sales)',
                    'Avg SP/LP': 'Ratio between selling price to listing price for a month',
                    'Avg DOM': 'Average number of days on the market in a month',
                    'index_Cp': 'Benchmark index for composite house for a month',
                   'index_SFD': 'Benchmark index for single family detached house for a month',
                   'index_SFA': 'Benchmark index for single family attached house for a month',
                   'index_Ap': 'Benchmark index for apartment house for a month',
                   'index_Th': 'Benchmark index for townhouse for a month',
                   'benchmark_Cp': 'Benchmark price for composite house for a month',
                   'benchmark_SFD': 'Benchmark price for single family detached house for a month',
                   'benchmark_SFA': 'Benchmark price for single family attached house for a month',
                   'benchmark_Ap': 'Benchmark price for apartment house for a month',
                   'benchmark_Th': 'Benchmark price for townhouse for a month',
                   'yrtoyr_chg_Cp': 'Year to year percent change in price for composite house for a month',
                   'yrtoyr_chg_SFD': 'Year to year percent change in price for single family detached house for a month',
                   'yrtoyr_chg_SFA': 'Year to year percent change in price for single family attached house for a month',
                   'yrtoyr_chg_Ap': 'Year to year percent change in price for apartment house for a month',
                   'yrtoyr_chg_Th': 'Year to year percent change in price for townhouse for a month'
                }

